### ISSUE TITLE
Kickass good job- question.

### ISSUE THREAD

**Issue by iamtimsson** [vddCore/AsusSupersetDecryptor#1]
What does it for buddey?
I am so glad for this win it is awesome: what's it for?

**Comment by vddCore** [comment]
The program in this repository allows a person to reconstruct the weird .zip (split into .enc and .dat) packages used by ASUS Armoury Crate installer into proper, browsable ones. This allows the user to extract drivers from installation packages for analysis without having to run their installer. You can download an example package with SuperSet ZIP files from the [Armoury Crate official website](https://dlcdnets.asus.com/pub/ASUS/mb/14Utilities/Armoury_Crate_Full_Installation_Package.zip) and see for yourself. The ZIPs this tool can reconstruct start with `SuperSet_`.

Hope I could clear it up enough.
